tasks:
  - name: Init and Run
    init: |
      nvm install 16
      npm run init
    command: |
      npm run dev
ports:
  - port: 8601
    onOpen: open-preview
vscode:
  extensions:
    - svelte.svelte-vscode
